version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
    labels:
      - "dependencies"
    open-pull-requests-limit: 3
    allow: 
      - dependency-name: "*"
      - dependency-type: "production"
