version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
    labels:
      - "chore: npm dependencies"
    open-pull-requests-limit: 3
